from pathlib import Path
import json,base64,html,zipfile
R=Path('/home/user/moko');D=R/'revision2';items=json.load(open(D/'manifest.json'))
def uri(path):return 'data:image/jpeg;base64,'+base64.b64encode(Path(path).read_bytes()).decode()
for i,it in enumerate(items):
 it['versions']=[{'name':'Обновлённая','image':uri(D/'thumbs'/it['file'])},{'name':'Исходная','image':uri(R/'originals'/(it['video']['id']+'.jpg'))}]
 if it['previous']:it['versions'].append({'name':'Первый концепт','image':uri(R/it['previous'])})
 if i==0:it['versions'].append({'name':'Чёрно-красная','image':uri(R/'branded/01_graph_brand.jpg')})
page='''<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MOKO — согласование обложек</title><style>
*{box-sizing:border-box}body{margin:0;background:#080d15;color:#f4f6fa;font:15px/1.5 system-ui,sans-serif}header,main,footer{max-width:1440px;margin:auto;padding:26px}header{padding-top:40px}h1{font-size:clamp(28px,4vw,46px);line-height:1.1;margin:20px 0 16px}h2{font-size:21px}p{color:#aeb8c7;max-width:860px}.eyebrow{color:#ed6262;font-size:12px;letter-spacing:2px;font-weight:700}.chips{display:flex;gap:8px;flex-wrap:wrap;margin:22px 0 0}button,.download{font:inherit;color:#e8ecf2;background:#172131;border:1px solid #2b394c;border-radius:9px;padding:10px 15px;cursor:pointer;text-decoration:none}button.active{background:#e7edf7;color:#080d15;border-color:#e7edf7}button:hover,.download:hover{border-color:#aab8cd}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:27px 22px}.card{min-width:0}.imagebutton{display:block;padding:0;border:0;width:100%;background:none;border-radius:9px;overflow:hidden}.card img{width:100%;display:block;aspect-ratio:16/9}.card h2{margin:12px 0 3px}.note{font-size:13px;color:#aeb8c7}.vtitle{font-size:13px;color:#7f8da2;margin-top:9px}.card .actions{display:flex;gap:8px;margin-top:14px}.actions button{font-size:13px;padding:7px 11px}dialog{background:#0b1220;color:white;border:1px solid #33415a;border-radius:16px;width:min(1240px,96vw);max-height:94vh;padding:22px}dialog::backdrop{background:#000c}.dialoghead{display:flex;gap:20px;align-items:start;justify-content:space-between;position:sticky;top:-22px;padding:14px 0;background:#0b1220;z-index:5}.dialoghead h2{margin:0;max-width:950px;font-size:20px}#tabs{margin:5px 0 19px;display:flex;gap:8px;flex-wrap:wrap}.bigimg{width:100%;display:block;border-radius:8px}.allversions{display:grid;grid-template-columns:1fr 1fr;gap:18px}.verlabel{font-size:13px;color:#aeb8c7;margin-bottom:8px}.warning{border-left:3px solid #d64545;padding:10px 14px;background:#141b28;color:#bcc6d5;font-size:13px;margin:18px 0}.legend{display:flex;flex-wrap:wrap;gap:18px;color:#b1bccb;font-size:13px}.dot{display:inline-block;width:9px;height:9px;margin-right:6px;border-radius:50%}.rule{height:1px;background:#223047;margin:24px 0}.foot{font-size:12px;color:#7f8da2}.close{padding:7px 13px;font-size:20px}.comparehint{font-size:13px;color:#aeb8c7}footer{padding-bottom:44px}a{color:#a7c9ff}@media(max-width:1050px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:640px){header,main,footer{padding:20px}.grid{grid-template-columns:1fr;gap:32px}dialog{padding:14px}.dialoghead{top:-14px}.allversions{grid-template-columns:1fr}.dialoghead h2{font-size:16px}button{font-size:13px}h1{margin-top:14px}}
</style><header><div class="eyebrow">MOKO / SYSTEMS · СОГЛАСОВАНИЕ 02</div><h1>Один канал.<br>Разные темы и композиции.</h1><p>Шесть пробных обложек. Вернули цветовые акценты, закрепили компактную подпись MOKO / SYSTEMS справа вверху и добавили разные композиции. Нажми на обложку, чтобы открыть её крупно и сравнить доступные версии.</p><div class="legend"><span><i class="dot" style="background:#b8eb55"></i>Уроки MOKO SE</span><span><i class="dot" style="background:#ff9a48"></i>Разработка</span><span><i class="dot" style="background:#55c9ff"></i>Практика</span><span><i class="dot" style="background:#ed6262"></i>События</span></div><div class="chips" id="filters"></div></header><main><div class="grid" id="grid"></div></main><footer><div class="rule"></div><h2>Что сравниваем</h2><p>① Узнаваемость канала. ② Различимость рубрик. ③ Читаемость заголовков на телефоне. ④ Баланс фото, иллюстрации и текста. Можно ответить номерами: «01 — оставить, 02 — крупнее заголовок…».</p><p class="comparehint">Стрим — формат, а не отдельная цветовая рубрика. Поэтому урок о драйвере и стрим о разработке плагина используют один оранжевый акцент. Telegram остаётся в зелёной учебной серии.</p><div class="warning">Все шесть — концепты, не готовая замена всего архива. В №04 лицо и фара пока из первого ИИ-концепта: для финала нужны реальные исходники. В №05 и №06 фотографии взяты из текущих обложек без генеративной перерисовки. Технические иллюстрации условные, не скриншоты интерфейсов.</div><p class="foot">Исходный знак MOKO — предоставленный SVG. Надпись набрана текстом, не является исходным фирменным словесным логотипом. Здесь показаны шесть роликов из первоначально собранной выборки в 30 видео, не весь канал. Файл работает без интернета.</p></footer><dialog id="dialog"><div class="dialoghead"><h2 id="title"></h2><button class="close" onclick="document.querySelector('dialog').close()" aria-label="Закрыть">×</button></div><div id="tabs"></div><div id="versions"></div><div class="warning" id="assetnote"></div><a class="download" id="download">Скачать обновлённую JPG</a><p class="foot">1280 × 720 · Концепт для согласования</p></dialog><script>const items=__DATA__;
const grid=document.getElementById('grid');const filters=document.getElementById('filters');const dialog=document.getElementById('dialog');let current=0;
function el(t,c,txt){const e=document.createElement(t);if(c)e.className=c;if(txt)e.textContent=txt;return e}
function render(cat='Все'){grid.innerHTML='';[...filters.children].forEach(b=>b.classList.toggle('active',b.textContent===cat));items.forEach((it,i)=>{if(cat!=='Все'&&it.category!==cat)return;const card=el('article','card');const b=el('button','imagebutton');b.setAttribute('aria-label','Открыть '+it.video.title);const img=el('img');img.src=it.versions[0].image;img.alt=it.video.title;b.append(img);b.onclick=()=>openCard(i);card.append(b,el('h2','',String(i+1).padStart(2,'0')+' / '+it.category),el('div','note',it.note),el('div','vtitle',it.video.title));const acts=el('div','actions');const full=el('button','','Открыть крупно');full.onclick=()=>openCard(i);const all=el('button','','Сравнить все версии · '+it.versions.length);all.onclick=()=>openCard(i,true);acts.append(full,all);card.append(acts);grid.append(card)})}
['Все','Уроки MOKO SE','Разработка','Практика','События'].forEach(c=>{const b=el('button','',c);b.onclick=()=>render(c);filters.append(b)});
function showVersion(v){const it=items[current];const box=document.getElementById('versions');box.innerHTML='';box.className=v===-1?'allversions':'';[...document.getElementById('tabs').children].forEach((b,j)=>b.classList.toggle('active',v===-1?j===it.versions.length:j===v));(v===-1?it.versions:[it.versions[v]]).forEach(a=>{const panel=el('div');panel.append(el('div','verlabel',a.name));const img=el('img','bigimg');img.src=a.image;img.alt=a.name+' — '+it.video.title;panel.append(img);box.append(panel)})}
function openCard(i,all=false){current=i;const it=items[i];document.getElementById('title').textContent=String(i+1).padStart(2,'0')+' / '+it.video.title;document.getElementById('assetnote').textContent=it.asset_note;const tabs=document.getElementById('tabs');tabs.innerHTML='';it.versions.forEach((a,j)=>{const b=el('button','',a.name);b.onclick=()=>showVersion(j);tabs.append(b)});const b=el('button','','Все рядом');b.onclick=()=>showVersion(-1);tabs.append(b);const dl=document.getElementById('download');dl.href=it.versions[0].image;dl.download=it.file;showVersion(all?-1:0);dialog.showModal();dialog.scrollTop=0}
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});render();</script></html>'''
page=page.replace('__DATA__',json.dumps(items,ensure_ascii=False).replace('</','<\\/'))
(D/'review.html').write_text(page)
with zipfile.ZipFile(D/'MOKO_series_v2.zip','w',zipfile.ZIP_DEFLATED) as z:
 for p in sorted((D/'thumbs').glob('*.jpg')):z.write(p,'thumbnails/'+p.name)
 z.write(D/'series_overview.jpg','series_overview.jpg');z.write(D/'review.html','review.html');z.write(R/'brand/logo.svg','logo.svg');z.write(D/'manifest.json','manifest.json')
print('Review bytes',len(page),'ZIP', (D/'MOKO_series_v2.zip').stat().st_size)
